version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  leaderboard-api:
    build: ./leaderboard-api
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  leaderboard-consumer:
    build: ./leaderboard-consumer
    depends_on:
      - kafka
      - redis